<script>
  // Full-text overlay for a Tyndale dictionary article. The Context card only ever shows a clamped
  // preview — articles run to 106k characters, which would bury every section below them — so
  // "Read more" and the supplement chips both open here instead of expanding in place.
  // `focusId` scrolls straight to one embedded chart/textbox, so clicking a chart chip lands on that
  // chart with the whole article still above it to scroll back through.
  import { parseArticleBlocks } from '../../lib/display.js';
  import RefText from '../common/RefText.svelte';

  const DICT_SOURCE = 'Tyndale Open Bible Dictionary · © 2023 Tyndale House Publishers · CC BY-SA 4.0';
  let { article, supplements = [], focusId = null, source = null, onclose } = $props();

  let blocks = $derived(parseArticleBlocks(article.body));

  let bodyEl = $state(null);
  // the target is looked up by data-sid rather than bound: Svelte 5 rejects a conditional
  // bind:this, and there is one element per supplement.
  $effect(() => {
    if (!bodyEl) return;
    const target = focusId && bodyEl.querySelector(`[data-sid="${CSS.escape(focusId)}"]`);
    if (target) target.scrollIntoView({ block: 'start', behavior: 'smooth' });
    else bodyEl.scrollTop = 0;
  });
</script>

<svelte:window onkeydown={(e) => { if (e.key === 'Escape') onclose?.(); }} />
<div class="backdrop" onclick={() => onclose?.()} role="presentation"></div>
<div class="modal" role="dialog" aria-modal="true" aria-label={article.title}>
  <div class="top">
    <h2 class="mtitle">{article.title}</h2>
    <button class="close" onclick={() => onclose?.()} aria-label="Close">✕</button>
  </div>

  <div class="scroll" bind:this={bodyEl}>
    {#each blocks as b}
      {#if b.kind === 'head'}
        <h3 class="mhead">{b.text}</h3>
      {:else if b.kind === 'item'}
        <p class="mitem"><RefText text={b.text} book={article.book ?? null} onnavigate={() => onclose?.()} /></p>
      {:else}
        <p class="mbody"><RefText text={b.text} book={article.book ?? null} onnavigate={() => onclose?.()} /></p>
      {/if}
    {/each}

    {#each supplements as s (s.id)}
      <div class="supp" data-sid={s.id}>
        <div class="supptitle">{s.kind === 'chart' ? '▦' : '▤'} {s.title}</div>
        <!-- charts are the only Tyndale content that cannot flatten to text. The markup is
             generated by our own build-time parser (tags whitelisted to table/tr/td/th, every
             attribute stripped), never raw vendor input, so {@html} has no untrusted source. -->
        {#if s.is_html}
          <div class="charttbl">{@html s.body}</div>
        {:else}
          <p class="mbody"><RefText text={s.body} onnavigate={() => onclose?.()} /></p>
        {/if}
      </div>
    {/each}

    <div class="src">
      <div class="srclbl">Source</div>
      {source ?? DICT_SOURCE}
    </div>
  </div>
</div>

<style>
  .backdrop { position: fixed; inset: 0; z-index: 80; background: rgba(0,0,0,.4); animation: fadeIn .18s ease; }
  .modal { position: fixed; z-index: 81; top: 50%; left: 50%; transform: translate(-50%, -50%);
    width: min(660px, calc(100vw - 40px)); max-height: calc(100vh - 80px);
    background: var(--panel); border: 1px solid var(--rule); border-radius: 12px;
    display: flex; flex-direction: column; box-shadow: 0 18px 60px rgba(0,0,0,.35);
    animation: pop .2s cubic-bezier(.22,1,.36,1); }
  @keyframes fadeIn { from { opacity: 0; } }
  @keyframes pop { from { opacity: 0; transform: translate(-50%, -48%) scale(.97); } }
  .top { display: flex; align-items: baseline; gap: 10px; padding: 14px 16px 10px;
    border-bottom: 1px solid var(--rule); }
  .mtitle { margin: 0; font-size: 15px; font-weight: 600; color: var(--ink); flex: 1; }
  .close { background: transparent; border: none; color: var(--dim); font-family: inherit;
    font-size: 13px; cursor: pointer; padding: 0 2px; }
  .close:hover { color: var(--ink); }
  /* the scroll container, not the modal, so the title bar stays put while the article scrolls */
  .scroll { overflow-y: auto; padding: 12px 16px 16px; }
  /* generous measure + spacing: these run to 20k characters and are read, not skimmed */
  .mbody { margin: 0 0 11px; font-size: 13.5px; line-height: 1.72; color: var(--ink); }
  .mhead { margin: 20px 0 7px; font-size: 12px; font-weight: 600; color: var(--b);
    font-variant: small-caps; letter-spacing: .06em; }
  .mhead:first-child { margin-top: 0; }
  .mitem { margin: 0 0 5px; padding-left: 12px; font-size: 13.5px; line-height: 1.6;
    color: var(--ink); }
  .supp { margin-top: 14px; padding-top: 10px; border-top: 1px solid var(--rule); scroll-margin-top: 4px; }
  .supptitle { font-size: 12.5px; color: var(--b); font-weight: 600; margin-bottom: 5px; }
  /* a chart body is leading prose followed by a table; without a size here the prose inherits the
     modal's base and renders noticeably larger than the article it belongs to */
  .charttbl { overflow-x: auto; font-size: 13px; line-height: 1.6; color: var(--ink); }
  .charttbl :global(table) { border-collapse: collapse; font-size: 11.5px; width: 100%; margin-top: 8px; }
  .charttbl :global(td), .charttbl :global(th) { border: 1px solid var(--rule);
    padding: 3px 6px; text-align: left; vertical-align: top; color: var(--ink); }
  .src { margin-top: 16px; padding-top: 10px; border-top: 1px solid var(--rule);
    font-size: 11px; line-height: 1.5; color: var(--dim); }
  .srclbl { font-variant: small-caps; letter-spacing: .05em; margin-bottom: 2px; }
</style>
